Hide dev-dependencies from old cargo
    error: failed to select a version for the requirement `clap = "^4"`
      candidate versions found which didn't match: 3.2.25, 3.2.24, 3.2.23, ...
      location searched: crates.io index
    required by package `criterion v0.5.0`
        ... which is depended on by `unicode-ident v1.0.8 (/home/runner/work/unicode-ident/unicode-ident)`