Raise minimum tested compiler to Rust 1.90
Required by today's release of roaring.

    error: rustc 1.86.0 is not supported by the following package:
      roaring@0.11.4 requires rustc 1.90.0
    Either upgrade rustc or select compatible dependency versions with
    `cargo update <name>@<current-ver> --precise <compatible-ver>`
    where `<compatible-ver>` is the latest version supporting rustc 1.86.0