Raise minimum tested compiler to 1.65
Required by version 0.10.2 of the `roaring` crate.

    error: package `roaring v0.10.2` cannot be built because it requires
    rustc 1.65.0 or newer, while the currently active rustc version is 1.64.0