Raise minimum tested compiler to rust 1.81
Required by `half`, which is a transitive dependency of `criterion`.

    error: package `half v2.5.0` cannot be built because it requires rustc 1.81 or newer, while the currently active rustc version is 1.74.1
    Either upgrade to rustc 1.81 or newer, or use
    cargo update half@2.5.0 --precise ver
    where `ver` is the latest version of `half` supporting rustc 1.74.1